import type { Metadata } from 'next';
import { ArrowLeft, ArrowUpRight, MapPin, Mail } from 'lucide-react';
export const metadata: Metadata={title:'Yizhan Zhang (Eden) — CV',description:'Landscape architecture and urban design: experience, education and skills.'};
const experience=[
 {name:'BIG — Bjarke Ingels Group',period:'July 2022 — Present',location:'London, UK',roles:['Landscape Designer · November 2024 — Present','Junior Urban Designer · July 2022 — November 2024'],points:['Landscape-led design across international masterplans, urban regeneration, mixed-use developments, hospitality, public realm and ecological restoration.','Design development balancing spatial quality, ecological performance and long-term sustainability.','Multidisciplinary collaboration from concept design and competitions through planning and detailed design.']},
 {name:'AECOM',period:'March 2021 — August 2021',location:'Shanghai, China',roles:['Landscape Architecture Intern'],points:['Contributed to four landscape projects across the Yangtze River Delta, leading concept design, schematic design and visualisation.','Worked on street-level guidelines, transit-oriented urban design, community masterplans and conceptual proposals.']},
 {name:'Lab D+H',period:'October 2020 — February 2021',location:'Shanghai, China',roles:['Landscape Architecture Intern'],points:['Contributed to regional landscape and urban design projects through schematic design, visualisation and presentation materials.']},
 {name:'Jolma Architects',period:'April 2020 — June 2020',location:'Helsinki, Finland',roles:['Landscape Architecture Intern'],points:['Worked on a large-scale urban and landscape design competition in Finland and an urban space competition in Abu Dhabi.']}
];
export default function CVPage(){return <main className="cv-page">
 <header className="detail-header"><a href="/" className="back-link"><ArrowLeft size={18}/> Back to world</a><a href="/" className="detail-brand">EDEN</a><span className="eyebrow">CURRICULUM VITAE</span></header>
 <section className="cv-intro"><div className="cv-intro-copy"><span className="eyebrow">LANDSCAPE ARCHITECTURE & URBAN DESIGN</span><h1>Yizhan Zhang <span className="cv-name-alias">(Eden)</span></h1><p className="cv-summary">Landscape architect and urban designer at BIG in London, working across large-scale masterplans, public realm, hospitality and mixed-use projects. My practice connects concept design and visual communication with the coordination and detail needed to bring landscapes into use.</p><div className="cv-contact"><span><MapPin size={16}/> London, United Kingdom</span><a href="mailto:edenzhang@gmail.com"><Mail size={16}/> edenzhang@gmail.com</a><a href="https://www.linkedin.com/in/edenzhang" target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={14}/></a></div></div><img className="cv-portrait" src="/images/profile.jpg" alt="Portrait of Yizhan Zhang (Eden)" width={784} height={823}/></section>
 <div className="cv-content"><section className="cv-experience"><h2>Experience</h2>{experience.map(job=><article className="cv-job" key={job.name}><div className="cv-job-meta"><span>{job.period}</span><span>{job.location}</span></div><h3>{job.name}</h3>{job.roles.map(role=><p className="cv-role" key={role}>{role}</p>)}<ul>{job.points.map(point=><li key={point}>{point}</li>)}</ul></article>)}</section>
 <aside className="cv-sidebar"><section><h2>Education</h2><div className="cv-qualification"><h3>MLA · Landscape Architecture</h3><p>The Bartlett School of Architecture, UCL</p><span>September 2019 — September 2021 · London</span><strong>Distinction</strong></div><div className="cv-qualification"><h3>BLA · Landscape Architecture</h3><p>Nanjing Forestry University</p><span>September 2015 — September 2019 · Nanjing</span></div></section>
 <section><h2>Professional development</h2><p>ALI · Associate of the Landscape Institute</p><p className="cv-muted">One-year route to CMLI</p></section>
 <section><h2>Software skills</h2><dl className="cv-tools"><div><dt>Adobe PS · AI · ID · PR · AE</dt><dd>Mastery</dd></div><div><dt>Rhino · SketchUp</dt><dd>Mastery</dd></div><div><dt>Enscape · Lumion · V-Ray</dt><dd>Advanced</dd></div><div><dt>AutoCAD · GIS · Grasshopper · Revit</dt><dd>Proficient</dd></div><div><dt>Microsoft Office Suite</dt><dd>Proficient</dd></div><div><dt>AI Visualization & Generative Design</dt><dd>Mastery</dd></div></dl></section>
 <section><h2>Languages</h2><p>English · Fluent, IELTS 7.0</p><p>Chinese (Mandarin) · Native</p></section><section><h2>Beyond the studio</h2><p>Basketball, football and badminton. Gardening, acoustic guitar, urban sketching and volunteering.</p></section></aside></div>
 <footer className="cv-footer"><a href="/" className="project-back-world"><ArrowLeft size={18}/> Back to world</a></footer>
 </main>}

