export const projects = [
 { id:'01', slug:'railway-central', key:'railway', title:'Railway Central Park & Plaza', subtitle:'Public realm industrial landscape', category:'Public realm', location:'York, United Kingdom', year:'2024', x:19, y:24, pages:[4,15], role:'Junior Landscape Designer', tasks:'GIS site analysis, landscape masterplan, 3D modelling, diagrams and CGI rendering.', description:'A former industrial rail landscape becomes a connected public realm. Central Park and Coal Drops Plaza bring together people, ecology and railway heritage, retaining rails, reusing materials and making space for nature.', theme:'Reconnecting people and place' },
 { id:'02', slug:'difc-masterplan', key:'difc', title:'DIFC Masterplan', subtitle:'Financial district pre-concept masterplan', category:'Urban design', location:'Dubai, United Arab Emirates', year:'2023–2024', x:49, y:22, pages:[16,21], role:'Junior Landscape Designer · Landscape Lead', tasks:'Landscape masterplan, public realm and circulation design, landscape chapter, diagrams and physical models.', description:'A mixed-use masterplan organised around a central Green Y. The landscape spine combines social, ecological and mobility infrastructure, extending across Sheikh Zayed Road to reconnect with the existing DIFC district.', theme:'A landscape at the heart of the city' },
 { id:'03', slug:'eastern-gateway-mountain', key:'mountain', title:'Eastern Gateway Mountain', subtitle:'Artificial mountain', category:'Feasibility study', location:'Riyadh, Saudi Arabia', year:'2022–2023', x:81, y:21, pages:[22,29], role:'Junior Urban Designer', tasks:'Option package leader, massing studies, diagrams, 3D modelling and CGI coordination.', description:'Excavation spoil is transformed into a landmark artificial mountain. The study explores Cave, Summit and Ridge concepts, with the Ridge selected for its identity, accessibility and integration of indoor and outdoor sports.', theme:'Making a mountain from the city' },
 { id:'04', slug:'mirage', key:'mirage', title:'Mirage', subtitle:'Concept vision for a self-sufficient remote resort', category:'Hospitality vision', location:'Saudi Arabia', year:'2023', x:83, y:48, pages:[30,39], role:'Junior Urban Designer', tasks:'Masterplan massing studies, facade pattern studies, 3D modelling and photorealistic site plans.', description:'A pre-concept vision for a self-sufficient remote resort. The proposal explores the relationship between desert terrain, myth and hospitality through the Carved City and A Thousand Columns.', theme:'An imagined city in the desert' },
 { id:'05', slug:'north-resort', key:'north-resort', title:'North Resort', subtitle:'Luxury resort design on a Red Sea island', category:'Hospitality landscape', location:'Red Sea, Saudi Arabia', year:'2024–2025', x:80, y:76, pages:[40,45], role:'Landscape Designer', tasks:'Amenity landscape design, Revit coordination, planting design, 3D modelling and in-house CGI.', description:'A coastal hospitality landscape within a confidential Red Sea island masterplan. Guest arrivals, pools, beachfront spaces and private villa gardens balance privacy, spatial hierarchy and the unfolding experience of the coast.', theme:'Where landscape meets the sea' },
 { id:'06', slug:'marina-boutique-hotel', key:'marina', title:'Marina Boutique Hotel', subtitle:'Concept design for a marina boutique hotel with amenities', category:'Hospitality landscape', location:'Red Sea, Saudi Arabia', year:'2024–2025', x:48, y:73, pages:[46,47], role:'Landscape Designer · Asset Lead', tasks:'Asset masterplan, project management, 3D modelling, in-house CGI, coordination and deliverables production.', description:'A seamless procession from marina to beach. A terraced landscape spine guides guests through pools, decks and native coastal planting, gradually unfolding views of the Red Sea.', theme:'A journey from marina to beach' },
 { id:'07', slug:'pumping-heterotopia', key:'heterotopia', title:'Pumping Heterotopia', subtitle:'Re-imagine the Fun Palace in Abbey Mill Pumping Station', category:'Graduate project', location:'London, United Kingdom', year:'2021–2022', x:17, y:67, pages:[48,54], role:'Individual MLA graduate project', tasks:'Bartlett School of Architecture, University College London. Landscape design, research, physical models and visual communication.', description:'Abbey Mill Pumping Station becomes a playful and educational public landscape. Inspired by Cedric Price’s Fun Palace, the proposal uses gravity, hydropower, natural ventilation and human interaction to bring industrial infrastructure into public life.', theme:'Infrastructure becomes a place to explore and interact' },
];
export type Project = typeof projects[number];
export const confidentiality = 'Some project names, client information, locations and data have been anonymised or modified in the original portfolio.';
